### ISSUE TITLE
sstableloader non-prepared batch statements does not handle identifiers with ":" in them

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla-tools-java#241] opened 2021-04-06 11:44 UTC
Because non-prepared batch statements cannot handle named variables, we do variable replacement in this mode (terrible, yes). The regex match does not deal with column/keyspace/table identifiers containing ":" (i.e. alternator). 
Need to do boundary match (lookahead/lookbehind).

**Comment by nyh** [comment] 2021-04-06 11:50
This is a duplicate of #230 with a more pin-pointed description, right?

**Comment by elcallio** [comment] 2021-04-06 11:54
Yes. #230 says "prepare", when in fact it is the _not_ preparing that screws us violently. :-)

**Comment by nyh** [comment] 2021-04-06 13:26
Fixed by commit 57eb143119e26c03c5b361f28a7cced56878e12a but not closed automatically due to a typo. So closing manually.

**Closed by nyh** 2021-04-06 13:26 UTC
