### ISSUE TITLE
Scylla 4.2: Fail to build unified deb

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla-tools-java#179] opened 2020-07-06 19:54 UTC
Similar to:
scylladb/scylla#6736
and to https://github.com/scylladb/scylla-jmx/issues/120

Scylla 4.2 fails to build unified-deb
Looks like some issue with - and ~

https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/unified-deb/13/console

```
22:47:30  '../scylla-tools_4.2.rc0-20200706.87d282935d2.orig.tar.gz' => '/jenkins/slave/workspace/scylla-4.2/unified-deb/scylla-tools-java/build/scylla-tools-package.tar.gz'
22:47:30  + cp -a scylla-tools/debian debian
22:47:30  + debuild -rfakeroot -us -uc
22:47:30  This package has a Debian revision number but there does not seem to be
22:47:30  an appropriate original tar file or .orig directory in the parent directory;
22:47:30  (expected one of scylla-tools_4.2~rc0-20200706.87d282935d2.orig.tar.gz, scylla-tools_4.2~rc0-20200706.87d282935d2.orig.tar.bz2,
22:47:30  scylla-tools_4.2~rc0-20200706.87d282935d2.orig.tar.lzma,  scylla-tools_4.2~rc0-20200706.87d282935d2.orig.tar.xz or scylla-package.orig)
22:47:30  continue anyway? (y/n) Use of uninitialized value $ans in pattern match (m//) at /usr/bin/debuild line 1009.
```

**Please also check version on machine-image.**
I don't open an issue there, as there is no issue I can point too.
Just think if could cause any problems.

**Comment by syuu1228** [comment] 2020-07-07 00:33
@hagitsegev the fix for this is already on PR but not yet merged: https://github.com/scylladb/scylla-tools-java/pull/178

@avikivity ping, we need this for Scylla 4.2

**Comment by syuu1228** [comment] 2020-07-07 00:39
> **Please also check version on machine-image.**
> I don't open an issue there, as there is no issue I can point too.
> Just think if could cause any problems.

I don't think it affects machine-image, because the issue is only happens on .deb package, but machine-image is only for CentOS.

**Comment by avikivity** [comment] 2020-07-09 10:18
It is merged.

**Closed by avikivity** 2020-07-09 10:18 UTC
Labels: backport 4.2, bug
