### ISSUE TITLE
After running sstabledump as root the owner of Summary.db file was changed

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla-tools-java#26] opened 2017-03-28 13:48 UTC
drwx------. 3 larisau larisau 4096 Mar 28 14:27 .
drwx------. 3 larisau larisau 4096 Mar 28 14:11 ..
-rw-r--r--. 1 larisau larisau   66 Mar 28 14:27 client_warnings-test-ka-1-CompressionInfo.db
-rw-r--r--. 1 larisau larisau   74 Mar 28 14:27 client_warnings-test-ka-1-Data.db
-rw-r--r--. 1 larisau larisau   10 Mar 28 14:27 client_warnings-test-ka-1-Digest.sha1
-rw-r--r--. 1 larisau larisau   16 Mar 28 14:27 client_warnings-test-ka-1-Filter.db
-rw-r--r--. 1 larisau larisau   36 Mar 28 14:27 client_warnings-test-ka-1-Index.db
-rw-r--r--. 1 larisau larisau   38 Mar 28 14:27 client_warnings-test-ka-1-Scylla.db
-rw-r--r--. 1 larisau larisau 4446 Mar 28 14:27 client_warnings-test-ka-1-Statistics.db
-rw-r--r--. 1 larisau larisau   56 Mar 28 14:27 client_warnings-test-ka-1-Summary.db
-rw-r--r--. 1 larisau larisau  101 Mar 28 14:27 client_warnings-test-ka-1-TOC.txt

[root@larisa ~]# /home/larisau/dev/scylla-tools-java/tools/bin/sstabledump /home/larisau/.ccm/scylla-stress/node1/data/client_warnings/test-4e3323d013a711e79f77000000000000/client_warnings-test-ka-1-Data.db
[
  {
    "partition" : {
      "key" : [ "1" ],
      "position" : 0
    },
    "rows" : [
      {
        "type" : "row",
        "position" : 62,
        "liveness_info" : { "tstamp" : "2017-03-28T11:12:31.771908Z" },
        "cells" : [
          { "name" : "val", "value" : "aaa", "tstamp" : "2017-03-28T11:13:36.701207Z" }
        ]
      }
    ]
  },
  {
    "partition" : {
      "key" : [ "2" ],
      "position" : 62
    },
    "rows" : [
      {
        "type" : "row",
        "position" : 124,
        "liveness_info" : { "tstamp" : "2017-03-28T11:12:31.771908Z" },
        "cells" : [
          { "name" : "val", "value" : "bbb", "tstamp" : "2017-03-28T11:13:36.701207Z" }
        ]
      }
    ]
  }
][root@larisa ~]# ls -la /home/larisau/.ccm/scylla-stress/node1/data/client_warnings/test-4e3323d013a711e79f77000000000000/
total 52
drwx------. 3 larisau larisau 4096 Mar 28 16:35 .
drwx------. 3 larisau larisau 4096 Mar 28 14:11 ..
-rw-r--r--. 1 larisau larisau   66 Mar 28 14:27 client_warnings-test-ka-1-CompressionInfo.db
-rw-r--r--. 1 larisau larisau   74 Mar 28 14:27 client_warnings-test-ka-1-Data.db
-rw-r--r--. 1 larisau larisau   10 Mar 28 14:27 client_warnings-test-ka-1-Digest.sha1
-rw-r--r--. 1 larisau larisau   16 Mar 28 14:27 client_warnings-test-ka-1-Filter.db
-rw-r--r--. 1 larisau larisau   36 Mar 28 14:27 client_warnings-test-ka-1-Index.db
-rw-r--r--. 1 larisau larisau   38 Mar 28 14:27 client_warnings-test-ka-1-Scylla.db
-rw-r--r--. 1 larisau larisau 4446 Mar 28 14:27 client_warnings-test-ka-1-Statistics.db
**-rw-r--r--. 1 root    root      72 Mar 28 16:35 client_warnings-test-ka-1-Summary.db**
-rw-r--r--. 1 larisau larisau  101 Mar 28 14:27 client_warnings-test-ka-1-TOC.txt
drwx------. 2 larisau larisau 4096 Mar 28 14:11 upload

**Comment by slivne** [comment] 2017-03-28 14:03
Its qorse then that the file was overwritten ...the size seems different

**Comment by slivne** [comment] 2017-03-30 11:10
I don't think this is a regression - I think it happend in previous versions as well

It seems that cassandra overwrites our summary for some reason.

I tested this with cassandra as well - if we move the Summary it willcreate a new Summary when running the tools 

I think we may also want to look at:
https://issues.apache.org/jira/browse/CASSANDRA-8616

The tools may be touching system tables / commitlogs

**Comment by larisau** [comment] 2017-04-04 14:56
The same problem happens running sstablerepairedset tool as root:
sstables before:
-rw-r--r--. 1 larisau larisau     176 Apr  4 17:47 keyspace1-standard1-ka-1-CRC.db
-rw-r--r--. 1 larisau larisau 2810000 Apr  4 17:47 keyspace1-standard1-ka-1-Data.db
-rw-r--r--. 1 larisau larisau      10 Apr  4 17:47 keyspace1-standard1-ka-1-Digest.sha1
-rw-r--r--. 1 larisau larisau   12512 Apr  4 17:47 keyspace1-standard1-ka-1-Filter.db
-rw-r--r--. 1 larisau larisau  240000 Apr  4 17:47 keyspace1-standard1-ka-1-Index.db
-rw-r--r--. 1 larisau larisau      38 Apr  4 17:47 keyspace1-standard1-ka-1-Scylla.db
**-rw-r--r--. 1 larisau larisau    4446 Apr  4 17:47 keyspace1-standard1-ka-1-Statistics.db**
-rw-r--r--. 1 larisau larisau    1790 Apr  4 17:47 keyspace1-standard1-ka-1-Summary.db
-rw-r--r--. 1 larisau larisau      89 Apr  4 17:47 keyspace1-standard1-ka-1-TOC.txt

sstables after:
-rw-r--r--. 1 larisau larisau     176 Apr  4 17:47 keyspace1-standard1-ka-1-CRC.db
-rw-r--r--. 1 larisau larisau 2810000 Apr  4 17:47 keyspace1-standard1-ka-1-Data.db
-rw-r--r--. 1 larisau larisau      10 Apr  4 17:47 keyspace1-standard1-ka-1-Digest.sha1
-rw-r--r--. 1 larisau larisau   12512 Apr  4 17:47 keyspace1-standard1-ka-1-Filter.db
-rw-r--r--. 1 larisau larisau  240000 Apr  4 17:47 keyspace1-standard1-ka-1-Index.db
-rw-r--r--. 1 larisau larisau      38 Apr  4 17:47 keyspace1-standard1-ka-1-Scylla.db
**-rw-r--r--. 1 root    root       4446 Apr  4 17:49 keyspace1-standard1-ka-1-Statistics.db**
-rw-r--r--. 1 larisau larisau    1790 Apr  4 17:47 keyspace1-standard1-ka-1-Summary.db
-rw-r--r--. 1 larisau larisau      89 Apr  4 17:47 keyspace1-standard1-ka-1-TOC.txt

**Comment by elcallio** [comment] 2017-04-05 15:58
The problem seems to be cassandra not understanding out summary files. 
Looking at https://github.com/scylladb/scylla-tools-java/blob/master/src/java/org/apache/cassandra/io/sstable/format/SSTableReader.java line 859,
It expects the remainder or the file to contain "bounds" info, including utf-8 encoded "disk access mode". We apparently do not include this, since the file ends here. Are we really writing kosher ka-format summary files?

**Comment by slivne** [comment] 2017-04-06 10:49
@raphaelsc / @glommer - are we missing something on our summary files ? - if so please open a bug about it and lets fix.

**Comment by glommer** [comment] 2017-04-06 12:53
@raphaelsc can you look at this ?

**Comment by raphaelsc** [comment] 2017-04-06 13:05
On Thu, Apr 6, 2017 at 9:53 AM, Glauber Costa <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> can you look at this ?
>

sure.

**Comment by slivne** [comment] 2018-06-26 15:14
We are pushing this after sstable 3 

calle did the analysis and found we may be missing something in the summary files that causes cassandra to rewrite the files.

we will recheck this on ma file format and then fix it if it does not work.

**Comment by tzach** [comment] 2018-08-13 08:47
@slivne @raphaelsc  is this relate to Apache Cassandra 3.x file format https://github.com/scylladb/scylla/issues/1969 or just to 3.11 Java tools  https://github.com/scylladb/scylla/issues/3686 ?

**Comment by slivne** [comment] 2018-10-16 08:29
wait for mc format to be default and then retest

**Comment by slivne** [comment] 2020-01-12 19:23
in mc format there seems to be no issue 

```
root@ip-10-0-0-9 data]# ls -lstra system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/
total 104
 4 drwxr-xr-x. 14 scylla scylla  4096 Jan 12 19:19 ..
 0 drwxr-xr-x.  2 scylla scylla     6 Jan 12 19:19 upload
 0 drwxr-xr-x.  2 scylla scylla     6 Jan 12 19:19 staging
 4 -rw-r--r--.  1 scylla scylla   102 Jan 12 19:20 mc-31-big-TOC.txt
 4 -rw-r--r--.  1 scylla scylla    86 Jan 12 19:20 mc-31-big-Index.db
 8 -rw-r--r--.  1 scylla scylla  4844 Jan 12 19:20 mc-31-big-Data.db
 4 -rw-r--r--.  1 scylla scylla    10 Jan 12 19:20 mc-31-big-Digest.crc32
 4 -rw-r--r--.  1 scylla scylla    79 Jan 12 19:20 mc-31-big-Summary.db
 4 -rw-r--r--.  1 scylla scylla   336 Jan 12 19:20 mc-31-big-Filter.db
 8 -rw-r--r--.  1 scylla scylla  6217 Jan 12 19:20 mc-31-big-Statistics.db
 4 -rw-r--r--.  1 scylla scylla    98 Jan 12 19:20 mc-31-big-CompressionInfo.db
56 -rw-r--r--.  1 scylla scylla 55694 Jan 12 19:20 mc-31-big-Scylla.db
 0 drwxr-xr-x.  2 scylla scylla     6 Jan 12 19:20 pending_delete
 4 drwxr-xr-x.  5 scylla scylla  4096 Jan 12 19:20 .
[root@ip-10-0-0-9 data]#date
Sun Jan 12 19:22:39 UTC 2020
[root@ip-10-0-0-9 data]# sstabledump system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/mc-31-big-Data.db 
.
.
.
s -lstra system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/ 
total 104
 4 drwxr-xr-x. 14 scylla scylla  4096 Jan 12 19:19 ..
 0 drwxr-xr-x.  2 scylla scylla     6 Jan 12 19:19 upload
 0 drwxr-xr-x.  2 scylla scylla     6 Jan 12 19:19 staging
 4 -rw-r--r--.  1 scylla scylla   102 Jan 12 19:20 mc-31-big-TOC.txt
 4 -rw-r--r--.  1 scylla scylla    86 Jan 12 19:20 mc-31-big-Index.db
 8 -rw-r--r--.  1 scylla scylla  4844 Jan 12 19:20 mc-31-big-Data.db
 4 -rw-r--r--.  1 scylla scylla    10 Jan 12 19:20 mc-31-big-Digest.crc32
 4 -rw-r--r--.  1 scylla scylla    79 Jan 12 19:20 mc-31-big-Summary.db
 4 -rw-r--r--.  1 scylla scylla   336 Jan 12 19:20 mc-31-big-Filter.db
 8 -rw-r--r--.  1 scylla scylla  6217 Jan 12 19:20 mc-31-big-Statistics.db
 4 -rw-r--r--.  1 scylla scylla    98 Jan 12 19:20 mc-31-big-CompressionInfo.db
56 -rw-r--r--.  1 scylla scylla 55694 Jan 12 19:20 mc-31-big-Scylla.db
 0 drwxr-xr-x.  2 scylla scylla     6 Jan 12 19:20 pending_delete
 4 drwxr-xr-x.  5 scylla scylla  4096 Jan 12 19:20 .

```

closing the issue

**Closed by slivne** 2020-01-12 19:23 UTC
Labels: bug
