### ISSUE TITLE
sstableloader does not support udts

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-tools-java#57] opened 2018-01-25 17:06 UTC
scylla version 2.1.rc0-0.20180102.f371d1788
scylla-tools-java version 8efa88d932c70d37da63afc704560854b5d52ef9
cassandra version used 3.0.11

created the following schema

```
CREATE KEYSPACE keyspace1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TYPE keyspace1.typeone (
    value int,
    attributeone tinyint
);

CREATE TYPE keyspace1.typetwo (
    id text,
    attributetwo frozen<typeone>,
    attributethree frozen<typeone>
);

CREATE TABLE keyspace1.tableone (
    key int PRIMARY KEY,
    datetime timestamp,
    new_quotes map<text, frozen<list<frozen<typetwo>>>>,
    provider text
)

```

inserted the following data

```
cqlsh> insert INTO keyspace1.tableone (key,new_quotes,provider) values (1,{'a': [{id:'b', attributetwo: {value:1,attributeone:1}, attributethree:{value:1, attributeone:1}}]} ,'text');
cqlsh> select * from keyspace1.tableone ;

 key | datetime | new_quotes                                                                                                 | provider
-----+----------+------------------------------------------------------------------------------------------------------------+----------
   1 |     null | {'a': [{id: 'b', attributetwo: {value: 1, attributeone: 1}, attributethree: {value: 1, attributeone: 1}}]} |     text

```

tried to upload into scylla

```
sstableloader keyspace1/tableone-263562f001ed11e894dfa151b4bed413/mc-1-big-Data.db -v -x -d 127.0.0.1
CQL: 'INSERT INTO keyspace1.tableone (provider,key) values (?,?) USING TIMESTAMP ?;' [text, 1, 1516898386504595]
Preparing: INSERT INTO keyspace1.tableone (provider,key) values (?,?) USING TIMESTAMP ?;
CQL: 'UPDATE keyspace1.tableone USING TIMESTAMP ? SET new_quotes[?] = ? WHERE key = ?;' [1516898386504595, a, [java.nio.HeapByteBuffer[pos=8 lim=47 cap=47]], 1]
Preparing: UPDATE keyspace1.tableone USING TIMESTAMP ? SET new_quotes[?] = ? WHERE key = ?;
```

although there seem to be and insert for the provider,key and update for the new_quotes - nothing is found in scylla

```
cqlsh> select * from keyspace1.tableone ;

 key | datetime | new_quotes | provider
-----+----------+------------+----------

(0 rows)
```
when trying and doing the same with cassandra 3.0.8

I do see some data
```
select * from keyspace1.tableone ;

 key | datetime | new_quotes | provider
-----+----------+------------+----------
   1 |     null |       null |     text

(1 rows)
```

yet the new_quotes data is not visible

**Comment by ishibaev** [comment] 2018-01-26 11:51
Hello! this is our keyspace. Sorry, I can't upload example of data (internal policy)
[fxa.keyspace.sql.txt](https://github.com/scylladb/scylla-tools-java/files/1667599/fxa.keyspace.sql.txt)

**Comment by ishibaev** [comment] 2018-01-26 12:00
I can upload this example with fake values (insert statement from sstableloader output) -
INSERT INTO fxa.market_data_increment (is_book,provider,instrument,datetime_id,datetime,nanos) values (?,?,?,?,?,?) USING TIMESTAMP ?;' ^C[true, MYPROVIDER, MY/TOOL, 20 19 04:06:56 MSK 2017, 868589000, 1507628450069886]
UPDATE fxa.market_data_increment 
SET del_quotes =  ['4'], new_quotes = {'a': [], 'b': [{id: '4', price: {value: 598775, power: -4}, amount: {value: 1000000, power: 0}}]}
WHERE provider = 'MYPROVIDER' AND instrument = 'MY/TOOL' AND datetime_id = '2017-04-19'  AND datetime = '2017-04-19 04:06:56+0300' AND nanos = 868589000;

select * from fxa.market_data_increment WHERE provider = 'MYPROVIDER' AND instrument = 'MY/TOOL' AND datetime_id = '2017-04-19'  AND datetime = '2017-04-19 04:06:56+0300';

**Comment by elcallio** [comment] 2018-01-29 14:08
The above example (shlomi's) works fine for me on master (last weeks). Is this specific to 2.1 branch? If so, given that sstableloader has not been changed in ages, is it something about udt:s in scylla?

**Comment by slivne** [comment] 2018-01-30 09:45
just filling info from ishibaev  on the user mailing list
their cassandra version:  Cassandra 3.11.1

**Comment by ishibaev** [comment] 2018-01-31 08:59
add info from me - I submitted my problem on scylla version 2.0.2...
slivne submit  this problem on 2.1

**Comment by ishibaev** [comment] 2018-02-01 10:03
Can I help somehow? make some research or tests, more info?

**Comment by slivne** [comment] 2018-02-01 21:29
@elcallio I tried again 

```
sstableloader keyspace1/tableone-bcb6ecf0079011e8b070d999c8ed4d9c/mb-1-big-Data.db -v -x -d 127.0.0.1
CQL: 'INSERT INTO keyspace1.tableone (provider,key) values (?,?) USING TIMESTAMP ?;' [text, 1, 1517517910242360]
Preparing: INSERT INTO keyspace1.tableone (provider,key) values (?,?) USING TIMESTAMP ?;
CQL: 'UPDATE keyspace1.tableone USING TIMESTAMP ? SET new_quotes[?] = ? WHERE key = ?;' [1517517910242360, a, [java.nio.HeapByteBuffer[pos=8 lim=47 cap=47]], 1]
Preparing: UPDATE keyspace1.tableone USING TIMESTAMP ? SET new_quotes[?] = ? WHERE key = ?;
[shlomi@sl-t-centos data]$ cqlsh
Connected to  at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> select * from keyspace1.tableone ;

 key | datetime | new_quotes | provider
-----+----------+------------+----------

(0 rows)
cqlsh> quit
[shlomi@sl-t-centos data]$ sstableloader keyspace1/tableone-bcb6ecf0079011e8b070d999c8ed4d9c/mb-1-big-Data.db -v  -d 127.0.0.1
CQL: 'INSERT INTO keyspace1.tableone (provider,key) values (?,?) USING TIMESTAMP ?;' [text, 1, 1517517910242360]
CQL: 'UPDATE keyspace1.tableone USING TIMESTAMP ? SET new_quotes[?] = ? WHERE key = ?;' [1517517910242360, a, [java.nio.HeapByteBuffer[pos=8 lim=47 cap=47]], 1]
[shlomi@sl-t-centos data]$ cqlsh
Connected to  at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> select * from keyspace1.tableone ;

 key | datetime | new_quotes                                                                                                 | provider
-----+----------+------------------------------------------------------------------------------------------------------------+----------
   1 |     null | {'a': [{id: 'b', attributetwo: {value: 1, attributeone: 1}, attributethree: {value: 1, attributeone: 1}}]} |     text

(1 rows)
cqlsh> 
```

The first attempt that FAILS is the one with prepared statements

The second attempt is WITHOUT prepared statements and it passes 

I tested this on 2.1.rc2-0.20180201.5444eead0

and also on

2.0.2-0.20171201.07b039f

using both cassandra 3.0.8 and 3.11.1

I was also able todo that with the sample data @ishibaev provided

```
[shlomi@sl-t-centos data]$ sstableloader fxa/market_data_increment-b93f1200079511e896c6511ef7daf110/mc-1-big-Data.db -v -x -d 127.0.0.1
CQL: 'INSERT INTO fxa.market_data_increment (is_book,provider,instrument,datetime_id,datetime,nanos) values (?,?,?,?,?,?) USING TIMESTAMP ?;' [true, MYPROVIDER, MYTOOL, A, Thu Jan 01 00:00:00 UTC 1970, 0, 1517520253866153]
Preparing: INSERT INTO fxa.market_data_increment (is_book,provider,instrument,datetime_id,datetime,nanos) values (?,?,?,?,?,?) USING TIMESTAMP ?;
CQL: 'UPDATE fxa.market_data_increment USING TIMESTAMP ? SET del_quotes[SCYLLA_TIMEUUID_LIST_INDEX(?)] = ?, new_quotes[?] = ?, new_quotes[?] = ? WHERE provider = ? AND instrument = ? AND datetime_id = ? AND datetime = ? AND nanos = ?;' [1517520346677522, 778a95e0-0796-11e8-96c6-511ef7daf110, 4, a, [], b, [java.nio.HeapByteBuffer[pos=8 lim=47 cap=47]], MYPROVIDER, MYTOOL, A, Thu Jan 01 00:00:00 UTC 1970, 0]
Preparing: UPDATE fxa.market_data_increment USING TIMESTAMP ? SET del_quotes[SCYLLA_TIMEUUID_LIST_INDEX(?)] = ?, new_quotes[?] = ?, new_quotes[?] = ? WHERE provider = ? AND instrument = ? AND datetime_id = ? AND datetime = ? AND nanos = ?;
[shlomi@sl-t-centos data]$ cqlsh 
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> select * from fxa.market_data_increment ;

 provider | instrument | datetime_id | datetime | nanos | del_quotes | is_book | new_quotes | raw_increment | raw_time
----------+------------+-------------+----------+-------+------------+---------+------------+---------------+----------

(0 rows)
cqlsh> quit
[shlomi@sl-t-centos data]$ sstableloader fxa/market_data_increment-b93f1200079511e896c6511ef7daf110/mc-1-big-Data.db -v  -d 127.0.0.1
CQL: 'INSERT INTO fxa.market_data_increment (is_book,provider,instrument,datetime_id,datetime,nanos) values (?,?,?,?,?,?) USING TIMESTAMP ?;' [true, MYPROVIDER, MYTOOL, A, Thu Jan 01 00:00:00 UTC 1970, 0, 1517520253866153]
CQL: 'UPDATE fxa.market_data_increment USING TIMESTAMP ? SET del_quotes[SCYLLA_TIMEUUID_LIST_INDEX(?)] = ?, new_quotes[?] = ?, new_quotes[?] = ? WHERE provider = ? AND instrument = ? AND datetime_id = ? AND datetime = ? AND nanos = ?;' [1517520346677522, 778a95e0-0796-11e8-96c6-511ef7daf110, 4, a, [], b, [java.nio.HeapByteBuffer[pos=8 lim=47 cap=47]], MYPROVIDER, MYTOOL, A, Thu Jan 01 00:00:00 UTC 1970, 0]
[shlomi@sl-t-centos data]$ cqlsh 
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> select * from fxa.market_data_increment ;

 provider   | instrument | datetime_id | datetime                 | nanos | del_quotes | is_book | new_quotes                                                                                       | raw_increment | raw_time
------------+------------+-------------+--------------------------+-------+------------+---------+--------------------------------------------------------------------------------------------------+---------------+----------
 MYPROVIDER |     MYTOOL |           A | 1970-01-01 00:00:00+0000 |     0 |      ['4'] |    True | {'a': [], 'b': [{id: '4', price: {value: 598775, power: -4}, amount: {value: 1000000, power: 0}}]} |          null |     null

(1 rows)
cqlsh> 
```

So @ishibaev can you please try and run sstableloader without the -x flag and provide your feedback it worked for me

@elcallio can you please check that you are able to run this with the -x and without it as well.

**Comment by ishibaev** [comment] 2018-02-02 12:07
@slivne  THanks!!! works without errors. I need time to check result from scylla, but now import process works without update errors.
Does this '-x' flag has strong performance  impact on data load pace? because we need to load several terabytes into scylla from cassandra...

**Comment by ishibaev** [comment] 2018-02-02 13:44
@slivne BUT! 
I have 239MB of SStables. for test load, and after one and  half hour  the load process was active.., it spend too much time just for 239MB (without  errors though)

**Comment by ishibaev** [comment] 2018-02-02 13:53
@slivne  and  I found strange  message or error.
My test load was with table - 
CREATE TABLE fxa.market_data_increment (
    provider text,
    instrument text,
    datetime_id text,
    datetime timestamp,
    nanos int,
    del_quotes list<text>,
    is_book boolean,
    new_quotes map<text, frozen<list<frozen<market_data_quote>>>>,
    raw_increment decimal,
    raw_time text,
    PRIMARY KEY ((provider, instrument, datetime_id), datetime, nanos)
) WITH CLUSTERING ORDER BY (datetime ASC, nanos ASC)
    AND bloom_filter_fp_chance = 0.1
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'incremental marked data'
    AND compaction = {'class': 'DateTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

sstableloader show messages 
com.datastax.driver.core.exceptions.InvalidQueryException: PRIMARY KEY column "nanos" cannot be restricted as preceding column "datetime" is not restricted

**Comment by ishibaev** [comment] 2018-02-02 15:00
@slivne  upload 239MB of SStables without '-v' flag  has  cost of 50 minutes... it's too bad

**Comment by slivne** [comment] 2018-02-02 18:48
The -x has a large effect on performance it enables prepared statements. We
will check why it does not work with it and fix that (i cant.provide an eta
before we know ehat broken)


Are you uploading a single sstable. If you are loading multiple sstables
you can upload each with a different sstableloader (parallising the process)

**Comment by elcallio** [comment] 2018-02-05 08:40
@ishibaev: The last error would indicate that the sstable presents that clustering for a row in such a manner that the loader does not join them into a single insert/update. Is there no way you could NDA the data in question to us?

**Comment by ishibaev** [comment] 2018-02-05 09:03
@elcallio I'm sorry, but business department not accept it already. I'll try again on this week

**Comment by elcallio** [comment] 2018-02-05 09:28
No problem, I'll try to generate a facsimile. If you do have time, could you get a verbose log from the offending run (the one with missing clustering)?

**Comment by elcallio** [comment] 2018-02-05 15:08
So, regarding the prepared statements issue: It seems we collide with the more strict type handling that the cassandra driver does for prepared statements (compared to non-prepared ones). Here, the driver assumes we've actually done UDT marshaling of real java objects, and will refuse to generate a serialization codec for anything else.  This does not work for us, we have no such types. And the data we provide is already in the expected wire format. 

I've sent a patch that addresses this and generates "fake" codecs that treat sstable UDT data as the blobs they are. The above example now works with prepared statements too.

**Comment by ishibaev** [comment] 2018-02-05 16:52
waiting in anticipation...

**Comment by elcallio** [comment] 2018-02-06 13:01
Regarding the clustering: I tried to reproduce it, creating an identical table, and creating and updating a few rows in it (spreading updates between sstables). I failed to get anything like the error you reported. I'm afraid I will need some more info on that one to figure it out.

**Comment by ishibaev** [comment] 2018-02-07 11:52
@elcallio  which info I can send to you?

**Comment by elcallio** [comment] 2018-02-07 11:56
Can you get a verbose log from the run that generates the error? It might help some.

**Comment by ishibaev** [comment] 2018-02-07 20:50
Whole log for my test more than 4gb. I'll cat some sstables and reload it with verbose

**Comment by ishibaev** [comment] 2018-02-08 16:26
@elcallio   Hello. May be I have a problem - I'm trying to load about 43MB sstables with verbose log messaging, but  log file size about 1.9GB. is it ok?

**Comment by slivne** [comment] 2018-02-08 16:39
@ishibaev you can upload the files using the following procedure http://docs.scylladb.com/operating-scylla/troubleshooting/report_scylla_problem/

(its meant t upload core files and system inf but you can also load a log file / sstable files in this manner)

**Comment by ishibaev** [comment] 2018-02-09 08:14
@elcallio I mean approval from security department before I can upload file... I'm not about technical problems...

**Comment by ishibaev** [comment] 2018-02-09 17:06
[sstlog.log.gz](https://github.com/scylladb/scylla-tools-java/files/1711808/sstlog.log.gz)
hello! I found problem sstables which made messages like -
com.datastax.driver.core.exceptions.InvalidQueryException: PRIMARY KEY column "nanos" cannot be restricted as preceding column "datetime" is not restricted
here it is verbose log

**Comment by elcallio** [comment] 2018-02-12 10:31
Not much to go on. I wonder if a clustering column was null and was left out of the sstable? Does not sound right though (I will try to repro). 
Not sure how much these tables change, but if you do a 

select * from fxa.market_data_increment where provider='MYPROVIDER1' and instrument='MY_TOOL2' and datetime_id='2017-01-03' and nanon=-1; 

in the database running on these sstables, what do you get? (my cql might be off here)

**Comment by elcallio** [comment] 2018-02-12 11:42
Another question: Is anything manipulating these tables via thrift? It should not be possible to null a clustering column via cql, but apparently thrift will allow it even thought it is logically illegal. 
If so, there might be a corner case where clustering columns actually are missing in tables that have been thrift-abused....

**Comment by elcallio** [comment] 2018-02-12 11:52
And just to clarify: If it really is the case that the sstable has rows where a clustering column is null, there is little the loader can do. Since we cannot insert a null value via cql here, there is no way (beyond adding yet another cql extension) to add the row to scylla.

**Comment by elcallio** [comment] 2018-02-13 12:43
If you have identified the sstable which generates the above log, instead of sending us the entire file, could you do a sstabledump (json text) of the file and send the parts with provider='MYPROVIDER1', instrument='MY_TOOL2'? It would be the second best thing to having the actual data to study.

**Comment by ishibaev** [comment] 2018-02-13 16:26
@elcallio 
 At  source (cassandra) side I can see nanos with '-1'. One row... I'll request the meaning of this value from business...
may be it's our personal pain and nothing more... I found this only once, although it's not possible to find all such rows with simple request...
  I think, if your patch can approve '-x' usage, it will be enough, until somebody ( or we) will find this problem again... 
p.s. dump here
[dump.txt](https://github.com/scylladb/scylla-tools-java/files/1720688/dump.txt)

**Comment by elcallio** [comment] 2018-02-14 08:29
Thanks for the dump. That did the trick. 
It seems "timestamp" is a litte nasty here. It is legal to do a set of a timestamp value to '' (empty string-ish), which translates to empty cell in sstable -> null value in reader. 
The table contains the right clustering, but the reader will give back null value here, and the logic in the translator breaks and thinks its reached end-of-restriction. 
Luckily, it seems we can get by this by in fact putting a null restriction in the insert statement in the Java code. Here it is legal enough, for timestamp at least. 
Patch being sent.

**Comment by ishibaev** [comment] 2018-02-15 09:20
@elcallio  hello! sorry, but how I can obtain patch? Or this patch will be included into next scylla  2.1 RCx version?

**Comment by elcallio** [comment] 2018-02-19 08:56
I'm assuming it will be in next (or some upcoming) release.

**Closed** 2018-02-19 13:01 UTC

**Comment by ishibaev** [comment] 2018-04-24 08:58
Scylla 2.1.2, RHEL 7.5.
Thanks for solution with 'NULL' in timestamp field which is a part of cluster key, but there was second field in cluster key, where 'NULL' value could be presented.
So, if the rows has cluster key with field (int type) ,which has value
-1
then sstableloader skip it.
Is it possible to find a way to import them too?

**Comment by elcallio** [comment] 2018-04-25 10:53
Well, patch was sent quite some time ago, but was not merged. I've pinged it.
