### ISSUE TITLE
stress ran out of memory during add_50_nodes_test

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla-tools-java#85] opened 2019-02-25 13:41 UTC
scylla version [a3a7bea](https://github.com/scylladb/scylla/commit/a3a7bea12f44a3315493469c2d4c028eb7ec5e56)
scylladb/scylla-dtest version [8126bd1](https://github.com/scylladb/scylla-dtest/commit/8126bd12f144afa6084f85c14a976e4c3f420297)

Seen in [dtest-release/41/testReport/update_cluster_layout_tests/TestLargeScaleCluster/add_50_nodes_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/41/testReport/update_cluster_layout_tests/TestLargeScaleCluster/add_50_nodes_test/):
```
Running with 609 threadCount
Running READ with 609 threads for 300000 iteration
type       total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb

stderr: java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:239)
	at org.apache.cassandra.stress.StressAction.runMulti(StressAction.java:146)
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:87)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
...
Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/update_cluster_layout_tests.py", line 1596, in add_50_nodes_test
    node2.stress(['read', 'cl=QUORUM', 'n=%s' % n, 'no-warmup', '-pop seq=1..%s' % n])
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 1126, in stress
    "stderr: {stderr}\n".format(**locals())
Stress command exited with error code: 1
```

Should we use different parameters to stress?
Should we catch this particular exception and just retry?  do that only in `add_50_nodes_test`?

**Comment by bhalevy** [comment] 2019-02-25 13:42
Meant to open in scylla-dtest (though a generic fix may end up in scylla-ccm)...

**Comment by slivne** [comment] 2019-03-05 14:41
closing this issue the problem is in dtest

**Closed by slivne** 2019-03-05 14:41 UTC
