### ISSUE TITLE
Add '--ignore-dead-nodes' option support to nodetool removenode

### ISSUE THREAD

**Issue by asias** [scylladb/scylla-tools-java#251] opened 2021-05-11 00:45 UTC
Since commit

```
commit 829b4c14380020fa4058335c4c43cefec135b3de
Author: Asias He <asias@scylladb.com>
Date:   Mon Nov 16 16:13:44 2020 +0800

    repair: Make removenode safe by default
```

Scylla added the ability to exclude dead nodes during removenode operation.

If the user want the removenode operation to succeed even if some of the nodes
are not available, the user has to explicitly pass a list of nodes that can be
skipped for the operation.

The nodetool option can be:
```
$ nodetool removenode --ignore-dead-nodes <list_of_dead_nodes_to_ignore> <host_id>
````

Example restful api:
    
```
$ curl -X POST "http://127.0.0.1:10000/storage_service/remove_node/?host_id=7bd303e9-4c7b-4915-84f6-343d0dbd9a49&ignore_nodes=127.0.0.3,127.0.0.5"
    
```

**Comment by tarzanek** [comment] 2022-02-01 16:47
it seems https://github.com/scylladb/scylla-jmx/pull/178/files adds support for option
but it doesn't really pass on the option to the REST API

```
[root@7cde2899a85b /]# nodetool removenode --ignore-dead-nodes 172.17.0.3,172.17.0.4 f9a3b363-f2dd-4ff0-a86b-27d4294e2983
nodetool: Scylla API server HTTP POST to URL '/storage_service/remove_node' failed: std::runtime_error (removenode[b31b7293-d7d9-4b41-b4cb-57c3d91fa72b]: Nodes={172.17.0.4} needed for removenode operation are down. It is highly recommended to fix the down nodes and try again. To proceed with best-effort mode which might cause data inconsistency, run nodetool removenode --ignore-dead-nodes <list_of_dead_nodes> <host_id>. E.g., nodetool removenode --ignore-dead-nodes 127.0.0.1,127.0.0.2 817e9515-316f-4fe3-aaab-b00d6f12dddd)
```

**Comment by tarzanek** [comment] 2022-02-01 16:48
while direct
```
curl -X POST "http://127.0.0.1:10000/storage_service/remove_node/?host_id=f9a3b363-f2dd-4ff0-a86b-27d4294e2983&ignore_nodes=172.17.0.4,172.17.0.3" 
```
worked 
(found by @fee-mendes  )

**Comment by bhalevy** [comment] 2022-02-01 17:44
> was that option tested with multiple ignore nodes IPs ? @bhalevy ?

Yes. It's being tested regularly.
See https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1092/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/test_simple_removenode_3_nodetool_True_/

**Comment by bhalevy** [comment] 2022-02-01 17:46
Duplicate of #225

**Comment by bhalevy** [comment] 2022-02-01 17:47
I'm closing this issue.

Please verify the versions of tools/java and jmx you're using
and if there's a problem, let's open a new issue for it.

**Closed** 2022-02-01 17:47 UTC
